POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyD6jWCFpnFmLmP1qJXAhwVAH6oQhncKVBk HTTP/1.1
Content-Type: application/json

{
    "email": "joao@teste.com",
    "password": "123456",
    "returnSecureToken": true
}


###

POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD6jWCFpnFmLmP1qJXAhwVAH6oQhncKVBk
Content-Type: application/json

{
    "email": "joao@teste.com",
    "password": "123456",
    "returnSecureToken": true
}